language: node_js

node_js:
  - 'stable'
  - '8'
  - '6'

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  yarn: true
  directories:
    - node_modules

script:
  - lerna run build --scope @scant/build-helper # build tool goes first
  - yarn install --force # re-link the builder cli
  - lerna run build --scope @scant/emitter # emitter needs to exist for history
  - yarn run test

branches:
  only:
    - master
    - /^v[0-9].*$/

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

before_script:
  - yarn run bootstrap
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
