language: node_js

node_js:
  - 'stable'
  - '8'
  - '6'

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn run test

branches:
  only:
    - master
    - /^v[0-9].*$/

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

before_script:
  - yarn run bootstrap
